#!/usr/bin/env bash
# Shared helpers, sourced by the other scripts/*.sh files. Not meant to be run directly.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/scripts/.env"

GITEA_URL="http://localhost:3000"
GITEA_ADMIN_USER="admin"
GITEA_ADMIN_PASSWORD="admin12345!"
GITEA_ADMIN_EMAIL="admin@example.com"
GITEA_OWNER="$GITEA_ADMIN_USER"
GITEA_REPO="violations-demo"
GITEA_TOKEN_NAME="violation-comments-cli"

log() {
  echo "[gitea] $*" >&2
}

# "sudo", or empty, depending on whether the current user can talk to the Docker daemon directly
# (no membership in the `docker` group means they can't). Run these scripts with or without sudo
# either way - this makes both work, for both `docker compose` and cleaning up files Docker
# created as root (e.g. an auto-vivified bind-mount directory). Fix it for good with:
#   sudo usermod -aG docker "$USER"   # then start a new login session (log out/in, or `newgrp docker`)
if docker info >/dev/null 2>&1; then
  SUDO=""
else
  SUDO="sudo"
fi

docker_compose() {
  $SUDO docker compose "$@"
}

wait_for_gitea() {
  log "Waiting for Gitea to become ready at $GITEA_URL ..."
  local i=0
  until curl -sf "$GITEA_URL/api/v1/version" >/dev/null 2>&1; do
    i=$((i + 1))
    if [ "$i" -ge 120 ]; then
      log "Gitea did not become ready in time. Check it's actually starting with 'docker compose ps -a' and 'docker compose logs gitea'."
      exit 1
    fi
    sleep 1
  done
  log "Gitea is up: $GITEA_URL"
}

write_env_file() {
  local content
  content="$(cat <<EOF
# Generated by scripts/gitea-setup.sh - do not commit, this holds a live API token.
GITEA_URL=$GITEA_URL
GITEA_OWNER=$GITEA_OWNER
GITEA_REPO=$GITEA_REPO
GITEA_PR_INDEX=$GITEA_PR_INDEX
GITEA_TOKEN=$GITEA_TOKEN
EOF
)"
  # A previous run may have written this as root (e.g. if it was invoked with sudo), leaving it
  # unwritable to a plain, non-sudo run now - or vice versa. Self-heal either way.
  if ! echo "$content" > "$ENV_FILE" 2>/dev/null; then
    echo "$content" | sudo tee "$ENV_FILE" >/dev/null
  fi
  sudo chown "$(id -u):$(id -g)" "$ENV_FILE" 2>/dev/null || true
  log "Wrote $ENV_FILE"
}

load_env_file() {
  if [ ! -f "$ENV_FILE" ]; then
    log "No $ENV_FILE found. Run scripts/gitea-setup.sh first."
    exit 1
  fi
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
}
