#!/usr/bin/env bash
# Shared helpers, sourced by the other scripts/*.sh files. Not meant to be run directly.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/scripts/.env"

GITEA_URL="http://localhost:3000"
GITEA_ADMIN_USER="admin"
GITEA_ADMIN_PASSWORD="admin12345!"
GITEA_ADMIN_EMAIL="admin@example.com"
GITEA_OWNER="$GITEA_ADMIN_USER"
GITEA_REPO="violations-demo"
GITEA_TOKEN_NAME="violation-comments-cli"

log() {
  echo "[gitea] $*" >&2
}

wait_for_gitea() {
  log "Waiting for Gitea to become ready at $GITEA_URL ..."
  local i=0
  until curl -sf "$GITEA_URL/api/v1/version" >/dev/null 2>&1; do
    i=$((i + 1))
    if [ "$i" -ge 120 ]; then
      log "Gitea did not become ready in time. Check 'docker compose logs gitea'."
      exit 1
    fi
    sleep 1
  done
  log "Gitea is up: $GITEA_URL"
}

write_env_file() {
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/gitea-setup.sh - do not commit, this holds a live API token.
GITEA_URL=$GITEA_URL
GITEA_OWNER=$GITEA_OWNER
GITEA_REPO=$GITEA_REPO
GITEA_PR_INDEX=$GITEA_PR_INDEX
GITEA_TOKEN=$GITEA_TOKEN
EOF
  log "Wrote $ENV_FILE"
}

load_env_file() {
  if [ ! -f "$ENV_FILE" ]; then
    log "No $ENV_FILE found. Run scripts/gitea-setup.sh first."
    exit 1
  fi
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
}
